/// Hive Types
const int HIVE_TYPE_ID_BOOK_SECTION_VO =1 ;
const int HIVE_TYPE_ID_BOOK_VO = 2;
const int HIVE_TYPE_ID_BUY_LINKS_VO =3 ;
const int HIVE_TYPE_ID_RESULT_VO = 4;
const int HIVE_TYPE_ID_SHELF_VO =5 ;
const int HIVE_TYPE_ID_ISBN_VO = 6;
const int HIVE_TYPE_ID_REVIEWS_VO = 7;
const int HIVE_TYPE_ID_SEARCH_INFO_VO = 8;
const int HIVE_TYPE_ID_ACCESS_INFO_VO = 9;
const int HIVE_TYPE_ID_EPUB_VO = 10;
const int HIVE_TYPE_ID_IMAGE_LINK_VO = 11;
const int HIVE_TYPE_ID_INDUSTRY_LINK_VO = 12;
const int HIVE_TYPE_ID_PANELIZATION_VO = 13;
const int HIVE_TYPE_ID_PDF_VO = 14;
const int HIVE_TYPE_ID_READING_MODE_VO = 15;
const int HIVE_TYPE_ID_SALE_INFO_VO = 16;
const int HIVE_TYPE_ID_SEARCH_BOOK_VO = 17;
const int HIVE_TYPE_ID_VOLUME_VO = 18;

/// Box Names
const String BOX_NAME_BOOK_SECTION_VO = "BOX_NAME_BOOK_SECTION_VO";
const String BOX_NAME_BOOK_VO = "BOX_NAME_BOOK_VO";
const String BOX_NAME_BUY_LINKS_VO = "BOX_NAME_BUY_LINKS_VO";
const String BOX_NAME_RESULT_VO = "BOX_NAME_RESULT_VO";
const String BOX_NAME_SHELF_VO = "BOX_NAME_SHELF_VO";
const String BOX_NAME_ISBN_VO = "BOX_NAME_ISBN_VO";
const String BOX_NAME_REVIEW_VO = "BOX_NAME_REVIEW_VO";
const String BOX_NAME_SEARCH_INFO_VO = "BOX_NAME_SEARCH_INFO_VO";

const String BOX_NAME_ACCESS_INFO_VO = "BOX_NAME_ACCESS_INFO_VO";
const String BOX_NAME_EPUB_VO = "BOX_NAME_EPUB_VO";
const String BOX_NAME_IMAGE_LINK_VO = "BOX_NAME_IMAGE_LINK_VO";
const String BOX_NAME_INDUSTRY_LINK_VO = "BOX_NAME_INDUSTRY_LINK_VO";
const String BOX_NAME_PANELIZATION_VO = "BOX_NAME_PANELIZATION_VO";
const String BOX_NAME_PDF_VO = "BOX_NAME_PDF_VO";
const String BOX_NAME_READING_MODE_VO = "BOX_NAME_READING_MODE_VO";
const String BOX_NAME_SALE_INFO_VO = "BOX_NAME_SALE_INFO_VO";
const String BOX_NAME_SEARCH_BOOK_VO = "BOX_NAME_SEARCH_BOOK_VO";
const String BOX_NAME_VOLUME_VO = "BOX_NAME_VOLUME_VO";

